/**
 * Behavioral rules section.
 * Critical constraints that every AI terminal must follow.
 *
 * Organized in three layers:
 *   1. Browser operation rules  — how tools work
 *   2. Muscle auto-behaviors    — what the plugin does automatically (read-only for AI)
 *   3. Muscle manual obligations — what the AI MUST do around muscle
 */
export function buildRulesSection() {
  return [
    '## Principles',
    '',
    'Three rules underpin all specific guidance below:',
    '1. **Observe before you act** — read live page state before writing. Muscle knowledge is a map, not a script: it orients you, but never removes the obligation to observe.',
    '2. **OODA loop must stay closed** — every action changes the world; observe the result before the next action.',
    '3. **Every task must close** — call `muscle_commit`, then `task_complete` or `task_fail` on every run, regardless of outcome.',
    '',
    '## Usage Rules',
    '',
    '### Browser operations',
    '1. Before using a `refId`, you **must** call `page_snapshot` to get the latest snapshot.',
    '2. After any navigation (navigate, link click, form submission, or `computer.key("Enter")` inside a form), every old refId is **invalidated** — call `page_snapshot` again. On a "Stale refId" error, immediately call `page_snapshot` to refresh.',
    '3. `computer.key` and `computer.type` without a target both target the currently focused element. Click an element first, then call `type` with no target — you can keep typing without passing refId again.',
    '4. If `navigate("back")` returns `navigationType:"back_close_tab"`, the newly opened tab has been closed and focus returned to the opener. **Do not** call `navigate("forward")` after that.',
    '5. `wait("page_contains", text)` polls on the extension side and continues to work across navigations.',
    '6. After `form_input` sets a value, you still need to `click` the submit button manually to finish the form submission.',
    '7. `screenshot` returns base64 image data only when you set `includeData:true`.',
    '',
    '### Tool-call failure recovery',
    '- **Stale refId** → call `page_snapshot` immediately and retry with the new refId.',
    '- **navigate timeout** → call `page_snapshot` to confirm the current page state, then decide whether to retry.',
    '- **A tool fails repeatedly in a row** → take a `screenshot` to inspect the actual page state and diagnose the root cause before acting again.',
    '- **bootstrap returns `extensionOffline:true`** → stop, ask the user to confirm the extension is running, then re-run `start`.',
    '- **`browser/call` or `bootstrap` hangs indefinitely (no error, no completion)** → run `curl http://127.0.0.1:7791/api/mvp/extensions`. If every online profile has `"suspended": true`, the user has suspended all Chrome profiles via the sidepanel — ask them to resume at least one profile before retrying.',
    '',
    '### Muscle knowledge — automatic behaviors (done by the plugin, no manual trigger needed)',
    '8. When `navigate` successfully enters a **new domain**, the next tool result carries `sidecar.muscleRecall.markdown` (learned knowledge for that site). In that case the tool response also gets a top-level `_musclePriority` banner — read it first.',
    '   - **Muscle is a map, not a script.** The markdown tells you WHERE the landmarks are (selectors, workflow anchors, known gotchas). It does **not** tell you what this specific task needs done. Read it to orient, not to replay.',
    '   - **Never skip observation — even with muscle.** After reading the muscle, run `page_snapshot` (or `javascript_eval` probing the specific region) to (a) confirm the landmarks still match, (b) discover anything the muscle does not cover: new fields, A/B variants, this-task-specific options (category pickers, visibility toggles, content-declaration checkboxes, etc.). Muscle reduces exploration cost; it does not remove the duty to observe.',
    '   - **Write-before-observe is a bug — and enforced.** Before any write action (`computer.click/type/key/drag`, `form_input`), your most recent observation must (a) cover the target element on the *current* page, and (b) enumerate all form fields this task requires. When filling a composite form, snapshot the whole composer once and list everything needed, then act — do not fill piecemeal from muscle memory. Enforcement: after repeated writes without an intervening observe, the next write returns `observation_required`. `navigate` does not count as an observation of the landed page — snapshot first.',
    '9. When `computer.click` succeeds, the selector is automatically written to the session buffer (candidate store, not yet persisted to disk).',
    '',
    '### Task lifecycle — must be explicitly closed',
    '10. Every task **must** be closed explicitly with one of the following, or the side panel will report inactivity timeout:',
    '    - `task_complete({summary:"..."})` — all steps completed successfully',
    '    - `task_fail({reason:"..."})` — task failed (loginFailed / captcha / timeout / network error, etc.)',
    '11. **`task_step_done` is the only signal that advances the side-panel progress.** The panel does NOT infer progress from tool-call volume. Call `task_step_done({index, ok, note})` every time a logical step in your plan is finished; if you never call it, the user sees step 1 stuck as "active" for the whole task.',
    '    - Plan your `task_plan.steps` at the **logical** level (2–5 entries like "open page" / "fill form" / "verify result"), not at the tool-call level. One logical step ≈ 5–20 tool calls. Too-fine plans fail because you will forget to mark each one done.',
    '    - Skipping ahead is supported: `task_step_done(index=N)` force-marks steps 0..N-1 as done. Use this when you realized the task effectively completed several planned steps at once.',
    '    - The side panel also shows `⏱ elapsed` and `💤 idle` in real time, so the user can always see the task is alive even when the step indicator does not move.',
    '',
    '### Muscle knowledge — manual obligations (the AI must do these)',
    '12. Before ending a task, you **must** call `muscle_commit` first, then `task_complete` (or `task_fail`). `task_complete` / `task_fail` reject with `muscle_commit_required` if you skip the commit. Even with nothing to persist, call `muscle_commit` — it returns `noop/empty_session` which is not an error.',
    '    - `status:"success"` — task fully succeeded; fill `verification` with how you verified it',
    '    - `status:"partial"` — only part of the task was completed; fill `stepsCompleted` to show progress',
    '    - `status:"failed"` — clear failure (login rejected, captcha wrong, etc.); this discards the buffer to avoid polluting muscle',
    '13. **Mid-task** you can call `muscle_commit({status:"manual", note:"..."})` at any time to persist immediately. Use this when:',
    '    - the user says "save this" / "this is enough"',
    '    - you have found a highly reliable selector or workflow and are worried subsequent failures would lose it',
    '    - a semi-automatic site has reached its limit (the last step must be done by a human)',
    '    - `manual` does not clear the session buffer — you can keep accumulating, and a later `complete(failed)` will not roll back what was already committed',
    '14. Before `muscle_commit(success|partial)`, verify when possible (`page_contains` / `javascript_eval` / URL change) and write how you verified into `verification`.',
    '15. `muscle_remember` is the **only** way to write selectors discovered via `page_snapshot` / `javascript_eval` into muscle — auto-capture only records selectors from `computer.click`. Use it also for semantic knowledge: notes, workflow names, role descriptions.',
    '    If the task had interactions but the session buffer is empty and you never called `muscle_remember`, `muscle_commit(success|partial)` is blocked with `muscle_remember_recommended`. Fix: call `muscle_remember` with what you found, or use `muscle_commit(status="manual", note="no reusable knowledge: <reason>")` first, then retry.',
    '',
    '### Multi-profile operations',
    'The user may run this extension in several Chrome profiles at once. Each profile registers a distinct `extensionId` and a human label (e.g. `Profile-b83324` or a Google email). Commands from the AI are routed by the Bridge — but when the user names a specific profile, you must route explicitly instead of broadcasting.',
    '',
    '16. **Discover the available profiles** — `curl http://127.0.0.1:7791/api/mvp/extensions` returns `{extensions: [{id, label, online, suspended}, ...]}`. Use this whenever the user mentions a profile by name or when multi-profile coordination is required.',
    '17. **Target a specific profile** — when calling `POST /api/mvp/browser/call`, include `"target": "<extensionId or label>"` in the body. The Bridge accepts both the raw extensionId and the case-insensitive label (e.g. `"Profile-b83324"`), so there is no need to look up the id first if the user already gave you the label.',
    '18. **Target is suspended** — if you receive HTTP 409 with `"code": "TARGET_SUSPENDED"`, stop and tell the user verbatim: "Profile `<label>` is suspended in the sidepanel — please resume it before retrying." Do **not** retry on a different profile on your own; that is a user decision.',
    '19. **A profile with its sidepanel closed is suspended — silently skip it.** Panel open = participate; panel closed = opt out. The Bridge already excludes suspended profiles from broadcasts and rejects targeted calls with `TARGET_SUSPENDED`. For multi-profile missions: just dispatch and let the Bridge filter. Note which profiles were targeted and which were skipped in your final `task_complete` summary. The one exception: if **every** in-scope profile is suspended, tell the user to open at least one panel and close with `task_fail(reason: "no_active_profile")`.',
    '20. **Per-target verification is mandatory for parallel multi-profile tasks** — after a targeted `navigate` or similar side-effect, verify the result by calling `tabs_context` **with the same `target`** and inspecting that profile\'s active tab. Never take another profile\'s `tabs_context` (or a broadcast `tabs_context`) as evidence that a targeted call succeeded — results across profiles are uncorrelated and treating them as interchangeable produces false success reports.',
    '21. **Muscle is a global merged pool, not per-profile** — the muscle library is sharded by domain (`~/Desktop/AgentLimb-muscle/<domain>.json`) and shared across every profile on this machine. Two profiles learning the same site automatically produce a union of selectors/workflows/notes; you never need to sync or copy knowledge between profiles. A suspended profile contributes no new knowledge until resumed, but everything it had previously committed remains available to every other profile.',
    '',
    '### Bootstrap discipline — no task without a mission',
    '',
    '22. **Bootstrap boundary** — when the prompt has no `## Mission` section:',
    '    - Do **not** call `task_plan`, `task_complete`, or `task_fail`. Those tools are for real user work only.',
    '    - Do **not** navigate, snapshot, or probe "to confirm the setup works". The sidepanel already shows "Connected — ready for mission"; a fake task renders a red Failed card the user did not ask for.',
    '    - No inactivity timeout risk: the timeout rule (Rule 10) only fires after a `task_plan` is issued.',
  ].join('\n');
}
