export const APP_ID = 'agentlimb.chrome_claudecode';
export const APP_NAME = 'AgentLimb Chrome ClaudeCode';
export const APP_VERSION = '0.1.4';

export const MESSAGE_TYPES = {
  // SW ← extension pages
  GET_RUNTIME_STATUS:     'AGENTLIMB_GET_RUNTIME_STATUS',
  GET_ACTIVE_TAB_CONTEXT: 'AGENTLIMB_GET_ACTIVE_TAB_CONTEXT',
  GET_PAGE_SNAPSHOT:      'AGENTLIMB_GET_PAGE_SNAPSHOT',
  EXECUTE_COMPUTER_ACTION:'AGENTLIMB_EXECUTE_COMPUTER_ACTION',
  LIST_HOST_TOOLS:        'AGENTLIMB_LIST_HOST_TOOLS',
  CALL_HOST_TOOL:         'AGENTLIMB_CALL_HOST_TOOL',
  PING:                   'AGENTLIMB_PING',
  OPEN_SIDE_PANEL:        'AGENTLIMB_OPEN_SIDE_PANEL',
  GET_ACTIVITY_LOG:       'AGENTLIMB_GET_ACTIVITY_LOG',
  GET_EXTENSION_IDENTITY: 'AGENTLIMB_GET_EXTENSION_IDENTITY',
  REGISTER_PANEL_WINDOW:  'AGENTLIMB_REGISTER_PANEL_WINDOW',
  // SW → extension pages (broadcast)
  NOTIFY_TOOL_CALLED:     'AGENTLIMB_NOTIFY_TOOL_CALLED',
  NOTIFY_TASK_PLAN:       'AGENTLIMB_NOTIFY_TASK_PLAN',
  NOTIFY_TASK_LIFECYCLE:  'AGENTLIMB_NOTIFY_TASK_LIFECYCLE',
};

export const CAPABILITIES = [
  'browser_host',
  'computer_control',
  'page_snapshot',
  'permissions',
  'product_shell',
];
